"""Initial reset

Revision ID: 73c77998cf91
Revises: 
Create Date: 2025-05-06 00:09:13.982461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c77998cf91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'user_id')
    # ### end Alembic commands ###
