"""tablo güncellemeleri

Revision ID: aea9827278c8
Revises: 73c77998cf91
Create Date: 2025-05-06 01:02:48.265468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aea9827278c8'
down_revision: Union[str, None] = '73c77998cf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_results_lesson_id_fkey', 'quiz_results', type_='foreignkey')
    op.drop_column('quiz_results', 'lesson_id')
    op.drop_column('quiz_results', 'user_answers')
    op.drop_column('quiz_results', 'generated_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_results', sa.Column('generated_questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('quiz_results', sa.Column('user_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('quiz_results', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('quiz_results_lesson_id_fkey', 'quiz_results', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
